#pragma once
#include <string>

// Generated by tools/embed_emitter_defaults.py from EmitterLibraryDefaults.json; edit the
// JSON and run the script instead of editing this file. The built-in Emitter Library
// (0 entries) in raw literals below the 16 KB string-literal limit.
namespace Workflow::EmitterLibrary
{
inline std::string DefaultsText()
{
    static const char* const parts[]={
        R"EL({"version":1,"emitters":[]})EL",
    };
    std::string text;for(const auto* part:parts)text+=part;return text;
}
}
