"""Embeds tools/asset_names/fr-en.txt in the editor DLL.

Writes Reloaded.Editor/AssetNameDictionary.gen.h. The release ships only the DLL,
so the dictionary travels inside it; users extend it with
System\\ReloadedEditor\\Translations\\fr-en.txt (same format, loaded after).

    python tools/asset_names/build_dictionary.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, 'fr-en.txt')
TARGET = os.path.join(HERE, '..', '..', 'Reloaded.Editor', 'AssetNameDictionary.gen.h')
LITERAL = 8000  # MSVC string literals stop at 16 KB
DELIMITER = 'FRN'


def main():
    text = open(SOURCE, encoding='ascii').read().replace('\r\n', '\n')
    if ')' + DELIMITER + '"' in text:
        sys.exit('fr-en.txt contains the raw-string delimiter')
    parts = []
    while text:
        cut = len(text) if len(text) <= LITERAL else text.rfind('\n', 0, LITERAL) + 1
        parts.append(text[:cut])
        text = text[cut:]
    lines = [
        '#pragma once',
        '#include <string>',
        '',
        '// Generated by tools/asset_names/build_dictionary.py from tools/asset_names/fr-en.txt;',
        '// do not edit. The built-in French->English dictionary for asset names.',
        'namespace AssetNames',
        '{',
        'inline std::string BuiltInDictionaryText()',
        '{',
        '    static const char* const parts[] = {',
    ]
    lines += [f'        R"{DELIMITER}({part}){DELIMITER}",' for part in parts]
    lines += [
        '    };',
        '    std::string text;',
        '    for (const auto* part : parts)',
        '        text += part;',
        '    return text;',
        '}',
        '}',
        '',
    ]
    with open(TARGET, 'w', encoding='ascii', newline='\r\n') as out:
        out.write('\n'.join(lines))
    print(f'{os.path.normpath(TARGET)}: {len(parts)} part(s)')


if __name__ == '__main__':
    main()
