"""Embeds the built-in Emitter Library into the editor DLL.

Reads Reloaded.Editor/EmitterLibraryDefaults.json ({"version":1,"emitters":[built-in entries]},
the schema in Reloaded.Editor/EmitterLibraryModel.h) and writes Reloaded.Editor/EmitterLibraryDefaults.h,
which holds the same document as compact ASCII JSON split into raw string literals below MSVC's
16 KB literal limit. The release zip carries only the exe, the DLL and README.md, so the defaults
must live in the DLL. Run it after changing the JSON, then run tools/test_workflow_tools.cmd:
EmitterLibraryModelTests validates every built-in entry.

    python tools/embed_emitter_defaults.py [defaults.json] [header.h]
"""
import json
import pathlib
import re
import sys

root = pathlib.Path(__file__).resolve().parent.parent
source = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else root / 'Reloaded.Editor' / 'EmitterLibraryDefaults.json'
target = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else root / 'Reloaded.Editor' / 'EmitterLibraryDefaults.h'

document = json.loads(source.read_text(encoding='utf-8'))
if not isinstance(document, dict) or document.get('version') != 1 or not isinstance(document.get('emitters'), list):
    sys.exit(f'{source}: expected {{"version":1,"emitters":[...]}}')
ids = set()
for entry in document['emitters']:
    entry.pop('builtin', None)  # in memory only
    identifier = entry.get('id', '')
    if not re.fullmatch(r'builtin\.[a-z0-9][a-z0-9_.-]{0,62}', identifier):
        sys.exit(f'{source}: {entry.get("name")!r} needs an id of the form builtin.<slug>')
    if identifier in ids:
        sys.exit(f'{source}: id {identifier} is used twice')
    ids.add(identifier)

text = json.dumps({'version': 1, 'emitters': document['emitters']}, ensure_ascii=True, separators=(',', ':'))
if ')EL"' in text:
    sys.exit('the JSON contains the raw-literal terminator )EL"')
size = 8000
parts = [text[i:i + size] for i in range(0, len(text), size)] or ['']
lines = [
    '#pragma once',
    '#include <string>',
    '',
    '// Generated by tools/embed_emitter_defaults.py from EmitterLibraryDefaults.json; edit the',
    '// JSON and run the script instead of editing this file. The built-in Emitter Library',
    f'// ({len(document["emitters"])} entries) in raw literals below the 16 KB string-literal limit.',
    'namespace Workflow::EmitterLibrary',
    '{',
    'inline std::string DefaultsText()',
    '{',
    '    static const char* const parts[]={',
]
lines += [f'        R"EL({part})EL",' for part in parts]
lines += [
    '    };',
    '    std::string text;for(const auto* part:parts)text+=part;return text;',
    '}',
    '}',
    '',
]
with open(target, 'w', encoding='ascii', newline='\r\n') as out:
    out.write('\n'.join(lines))
print(f'{target}: {len(document["emitters"])} entries, {len(text)} bytes in {len(parts)} literal(s)')
